name: Coverage

on: [push, pull_request]

jobs:
  codecov:
    name: codecov
    runs-on: ubuntu-latest
    services:
      minio:
        # edge-cicd is a modified image that doesn't require us to pass the `server` command when running the container.
        image: minio/minio:edge-cicd
        options: >-
          --health-cmd "curl http://localhost:9000/minio/health/live"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 19000:9000
    steps:
      - uses: actions/checkout@v4

      - name: Load .env file
        uses: cardinalby/export-env-action@v2
        with:
          envFile: .env

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOLANG_VERSION }}
          cache: false

      - name: Generate coverage report
        run: |
          go test -race ./... -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella
